version: '3.7'

networks:
  kong-fc:
    external: true

services:
  payever:
    build: 
      context: .
      dockerfile: ./.docker/dockerfiles/Dockerfile
    restart: always
    tty: true
    container_name: payever-assessment
    networks:
      - kong-fc
    volumes:
      - .:/usr/payever-assessment/app
    ports:
      - 3000:3000
    environment:
      NODE_ENV: development
      PORT: 3000
    extra_hosts:
      - host.docker.internal:host-gateway
      